# Dataset paths
data_dir: "../data/raw/mapillary_dataset"
processed_dir: "../data/processed"
models_dir: "../models"
logs_dir: "../logs"
results_dir: "../results"

# Training parameters
batch_size: 8  # Increased batch size with gradient accumulation
test_batch_size: 4
epochs: 50  
lr: 0.001
seed: 1
log_interval: 10
no_cuda: False
gradient_accumulation_steps: 4  # Simulate larger batch size

# Learning rate scheduler
lr_scheduler:
  step_size: 10
  gamma: 0.1

# Early stopping
early_stopping:
  patience: 5
  min_delta: 0.001

# Model parameters
num_classes: 3  # Adjust based on your dataset

# Data augmentation and preprocessing
image_size: [512, 1024]  # Lower resolution for training
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
data_augmentation:
  RandomHorizontalFlip: True
  RandomVerticalFlip: True
  RandomRotation: 10
  ColorJitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1