# Dataset paths
data_dir: "data/StreetSurfaceVis_1024"
processed_dir: "data/processed"
models_dir: "models"
logs_dir: "logs"
results_dir: "results"

# Training parameters
batch_size: 32
test_batch_size: 32
epochs: 30
lr: 0.001
seed: 1
log_interval: 200
no_cuda: False

# Model parameters
model_name: "efficientnet"
num_classes: 10  # Adjust based on your dataset

# Data augmentation and preprocessing
image_size: 224
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]