# Dataset paths
data_dir: "data/raw/StreetSurfaceVis_1024"
processed_dir: "data/processed"
models_dir: "models"
logs_dir: "logs"
results_dir: "results"

# Training parameters
batch_size: 16  # Reduced batch size for high-resolution images
test_batch_size: 16
epochs: 80  # Reduced epochs
lr: 0.001
seed: 1
log_interval: 10
no_cuda: False
gradient_accumulation_steps: 4  # Simulate larger batch size
max_grad_norm: 1.0  # Gradient clipping

# Learning rate scheduler
lr_scheduler:
  step_size: 10
  gamma: 0.1

# Early stopping
early_stopping:
  patience: 5
  min_delta: 0.001

# Model parameters
model_name: "efficientnet"
num_classes: 5  # Number of road surface types

# Data augmentation and preprocessing
image_size: 512  # Lower resolution for training
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]
data_augmentation:
  RandomHorizontalFlip: True
  RandomVerticalFlip: True
  RandomRotation: 10
  ColorJitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
  RandomResizedCrop:
    size: 512
    scale: [0.8, 1.0]