name: geoai
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=1.12.1
  - torchvision=0.13.1
  - pandas=1.5.0
  - scikit-learn=1.1.2
  - plotly=5.10.0
  - jupyter
  - numpy
  - matplotlib
  - pip
  - pip:
    - opencv-python
    - segmentation_models_pytorch